<template>
  <nuxt-link to="/">
    <img
      alt="Logo"
      src="data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iOTYiIGhlaWdodD0iNzIiIHZpZXdCb3g9IjAgMCA5NiA3MiIgdmVyc2lvbj0iMSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KICA8ZyBmaWxsPSJub25lIiBmaWxsLXJ1bGU9ImV2ZW5vZGQiPgogICAgPHBhdGggZD0iTTYgNjZoMjNsMS0zIDIxLTM3TDQwIDYgNiA2NnpNNzkgNjZoMTFMNjIgMTdsLTUgOSAyMiAzN3Yzek01NCAzMUwzNSA2NmgzOHoiLz4KICAgIDxwYXRoIGQ9Ik0yOSA2OXYtMS0ySDZMNDAgNmwxMSAyMCAzLTZMNDQgM3MtMi0zLTQtMy0zIDEtNSAzTDEgNjNjMCAxLTIgMyAwIDYgMCAxIDIgMiA1IDJoMjhjLTMgMC00LTEtNS0yeiIgZmlsbD0iIzAwQzU4RSIvPgogICAgPHBhdGggZD0iTTk1IDYzTDY3IDE0YzAtMS0yLTMtNS0zLTEgMC0zIDAtNCAzbC00IDYgMyA2IDUtOSAyOCA0OUg3OWE1IDUgMCAwIDEgMCAzYy0yIDItNSAyLTUgMmgxNmMxIDAgNCAwIDUtMiAxLTEgMi0zIDAtNnoiIGZpbGw9IiMxMDg3NzUiLz4KICAgIDxwYXRoIGQ9Ik03OSA2OXYtMS0yLTNMNTcgMjZsLTMtNi0zIDYtMjEgMzctMSAzYTUgNSAwIDAgMCAwIDNjMSAxIDIgMiA1IDJoNDBzMyAwIDUtMnpNNTQgMzFsMTkgMzVIMzVsMTktMzV6IiBmaWxsPSIjRkZGIiBmaWxsLXJ1bGU9Im5vbnplcm8iLz4KICA8L2c+Cjwvc3ZnPgo="
    >
  </nuxt-link>
</template>

<style lang="scss" scoped>
  img {
    width: 100%;
    height: auto;
    object-fit: cover;
  }
</style>
